apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: invites
spec:
  hosts:
    - invites
  http:
    - route:
        - destination:
            host: invites
      retries:
        attempts: 3
        perTryTimeout: 2s
        retryOn: connect-failure,refused-stream,503
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: invites
spec:
  host: invites
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-from-outside
  namespace: communicator-dev
spec:
  selector:
    matchLabels:
      app: invites
  action: DENY
  rules:
    - from:
        - source:
            notPrincipals:
              - "cluster.local/ns/communicator-dev/sa/servers"
      to:
        - operation:
            paths: ["/*"]
            methods: ["DELETE"]
        - operation:
            paths: ["/"]
            methods: ["POST"]
        - operation:
            paths: ["/servers/*"]
            methods: ["GET"]
